### ISSUE TITLE
Planned to maintain this?

### ISSUE THREAD

**Issue by brnl** [Starttoaster/nfs-subdir-external-provisioner#11]
Hi Starttoaster, I stumbled on your fork in [kubernetes-sigs/nfs-subdir-external-provisioner/issues/330](https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/330). Your work looks great, for what I can see, so I would like to know if you plan to maintain it from now on. Hopefully the original authors come back but it looks quite abandoned for now.

Thanks so far!

**Comment by Starttoaster** [comment]
Hey there @brnl glad you found me. Yeah, I plan on maintaining this from now on with one asterisk there. I will maintain the code in-so-far as keeping up with security updates, Golang dependency updates, etc., but the feature-set will likely be staying the same.

**Comment by brnl** [comment]
That is amazing news. You've been running it for a few months now, how is the stability?

And one thing that's not really clear to me: The repo and image tag in the helm chart seem to be still 4.0.2. Is that correct and as intended or am I missing something?
```yml
image:
  repository: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner
  tag: v4.0.2
  pullPolicy: IfNotPresent
```
